name: Deploy docs to Neocities
on:
  push:
    branches: [main]
jobs:
  deploy_to_neocities:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - run: mkdir public && .github/mddocs sqddl.md public/sqddl.html
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: public
